name: autoupdate

on:
  workflow_dispatch:
  

permissions:
  contents: write

jobs:

  build-aarch64:
  
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4


    - name: Edit distro_plugins
      run: |
        RELTAG=$(curl -s https://api.github.com/repos/<owner>/<repo>/releases/latest \
        | grep '"tag_name":' \
        | cut -d'"' -f4)

        echo "REF_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        chmod +w "$GITHUB_WORKSPACE/scripts/portadesx.sh"

        sed -i "2s|.*|TARBALL_URL['aarch64']=\"https://github.com/portadesx/portadesx/releases/download/$RELTAG/portadesx-aarch64.tar.xz\"|" "$GITHUB_WORKSPACE/scripts/portadesx.sh"
        sed -i "3s|.*|TARBALL_URL['arm']=\"https://github.com/portadesx/portadesx/releases/download/$RELTAG/portadesx-armhf.tar.xz\"|" "$GITHUB_WORKSPACE/scripts/portadesx.sh"
        sed -i "4s|.*|TARBALL_URL['x86_64']=\"https://github.com/portadesx/portadesx/releases/download/$RELTAG/portadesx-x86_64.tar.xz\"|" "$GITHUB_WORKSPACE/scripts/portadesx.sh"

        sed -i "5s|.*|TARBALL_SHA256['aarch64']=\"${AARCH64SHA256}\"|" "$GITHUB_WORKSPACE/scripts/portadesx.sh"
        sed -i "6s|.*|TARBALL_SHA256['arm']=\"${ARMHFSHA256}\"|" "$GITHUB_WORKSPACE/scripts/portadesx.sh"
        sed -i "7s|.*|TARBALL_SHA256['x86_64']=\"${X8664SHA256}\"|" "$GITHUB_WORKSPACE/scripts/portadesx.sh"

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "distro_plugins Auto-Update"
        git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
